--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ONE_TIME_TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ONE_TIME_TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"SERVICE_ID" NUMBER, 
	"AMOUNT" NUMBER(10,2), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ONE_TIME_TRANSACTIONS
SET DEFINE OFF;
Insert into SYSTEM.ONE_TIME_TRANSACTIONS (TRANSACTION_ID,SUBSCRIBER_ID,SERVICE_ID,AMOUNT,CREATED_AT) values (1,1,2,500,to_date('19-MAY-26','DD-MON-RR'));
Insert into SYSTEM.ONE_TIME_TRANSACTIONS (TRANSACTION_ID,SUBSCRIBER_ID,SERVICE_ID,AMOUNT,CREATED_AT) values (2,1,2,500,to_date('19-MAY-26','DD-MON-RR'));
Insert into SYSTEM.ONE_TIME_TRANSACTIONS (TRANSACTION_ID,SUBSCRIBER_ID,SERVICE_ID,AMOUNT,CREATED_AT) values (3,1,2,500,to_date('19-MAY-26','DD-MON-RR'));
Insert into SYSTEM.ONE_TIME_TRANSACTIONS (TRANSACTION_ID,SUBSCRIBER_ID,SERVICE_ID,AMOUNT,CREATED_AT) values (4,1,2,500,to_date('19-MAY-26','DD-MON-RR'));
Insert into SYSTEM.ONE_TIME_TRANSACTIONS (TRANSACTION_ID,SUBSCRIBER_ID,SERVICE_ID,AMOUNT,CREATED_AT) values (5,1,2,500,to_date('19-MAY-26','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C008233
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008233" ON "SYSTEM"."ONE_TIME_TRANSACTIONS" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ONE_TIME_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ONE_TIME_TRANSACTIONS" ADD PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ONE_TIME_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ONE_TIME_TRANSACTIONS" ADD FOREIGN KEY ("SUBSCRIBER_ID")
	  REFERENCES "SYSTEM"."SUBSCRIBER" ("SUBSCRIBER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."ONE_TIME_TRANSACTIONS" ADD FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "SYSTEM"."SERVICES" ("SERVICE_ID") ENABLE;
