--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SERVICES" 
   (	"SERVICE_ID" NUMBER, 
	"SERVICE_NAME" VARCHAR2(100 BYTE), 
	"SERVICE_TYPE" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(10,2), 
	"STATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SERVICES
SET DEFINE OFF;
Insert into SYSTEM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS) values (2,'Kontorlu','ONE_TIME',500,'ACTIVE');
Insert into SYSTEM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS) values (6,'100dk konusma','ONE_TIME',100,'ACTIVE');
--------------------------------------------------------
--  DDL for Index SYS_C008228
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008228" ON "SYSTEM"."SERVICES" ("SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SERVICES" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SERVICES" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SERVICES" ADD CHECK (
        service_type IN ('SUBSCRIPTION','ONE_TIME')
    ) ENABLE;
  ALTER TABLE "SYSTEM"."SERVICES" ADD CHECK (
        status IN ('ACTIVE','PASSIVE')
    ) ENABLE;
  ALTER TABLE "SYSTEM"."SERVICES" ADD PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
