--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBSCRIBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBSCRIBER" 
   (	"SUBSCRIBER_ID" NUMBER, 
	"MSISDN" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER(10,2) DEFAULT 0, 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SUBSCRIBER
SET DEFINE OFF;
Insert into SYSTEM.SUBSCRIBER (SUBSCRIBER_ID,MSISDN,BALANCE,STATUS,CREATED_AT) values (1,'905551112233',48500,'ACTIVE',to_date('19-MAY-26','DD-MON-RR'));
Insert into SYSTEM.SUBSCRIBER (SUBSCRIBER_ID,MSISDN,BALANCE,STATUS,CREATED_AT) values (4,'05338555554',1000,null,to_date('19-MAY-26','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C008222
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008222" ON "SYSTEM"."SUBSCRIBER" ("SUBSCRIBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008223
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008223" ON "SYSTEM"."SUBSCRIBER" ("MSISDN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSCRIBER" MODIFY ("MSISDN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBSCRIBER" ADD CHECK (status IN ('ACTIVE','PASSIVE')) ENABLE;
  ALTER TABLE "SYSTEM"."SUBSCRIBER" ADD PRIMARY KEY ("SUBSCRIBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SUBSCRIBER" ADD UNIQUE ("MSISDN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSCRIBER" ADD CONSTRAINT "FK_SUBSCRIBER_USER" FOREIGN KEY ("SUBSCRIBER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
