--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBSCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBSCRIPTIONS" 
   (	"SUBSCRIPTION_ID" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"SERVICE_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SUBSCRIPTIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008230
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008230" ON "SYSTEM"."SUBSCRIPTIONS" ("SUBSCRIPTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUBSCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSCRIPTIONS" ADD CHECK (
        status IN ('ACTIVE','CANCELLED')
    ) ENABLE;
  ALTER TABLE "SYSTEM"."SUBSCRIPTIONS" ADD PRIMARY KEY ("SUBSCRIPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBSCRIPTIONS" ADD FOREIGN KEY ("SUBSCRIBER_ID")
	  REFERENCES "SYSTEM"."SUBSCRIBER" ("SUBSCRIBER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."SUBSCRIPTIONS" ADD FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "SYSTEM"."SERVICES" ("SERVICE_ID") ENABLE;
