--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUDIT_LOGS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AUDIT_LOGS" 
   (	"LOG_ID" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"MESSAGE" VARCHAR2(500 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"ENTITY_TYPE" VARCHAR2(50 BYTE), 
	"ENTITY_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AUDIT_LOGS
SET DEFINE OFF;
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (1,null,'LOGIN','Successful login for user: admin',to_date('19-MAY-26','DD-MON-RR'),null,null);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (2,null,'LOGIN','Successful login for user: admin',to_date('19-MAY-26','DD-MON-RR'),null,null);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (3,null,'LOGIN','Successful login for user: admin',to_date('19-MAY-26','DD-MON-RR'),null,null);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (4,null,'LOGIN','Successful login for user: admin',to_date('19-MAY-26','DD-MON-RR'),null,null);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (5,1,'PURCHASE','Servis başarıyla satın alındı.',to_date('19-MAY-26','DD-MON-RR'),'SERVICE',2);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (6,1,'PURCHASE','Servis başarıyla satın alındı.',to_date('19-MAY-26','DD-MON-RR'),'SERVICE',2);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (7,1,'PURCHASE','Servis başarıyla satın alındı.',to_date('19-MAY-26','DD-MON-RR'),'SERVICE',2);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (8,1,'PURCHASE','Servis başarıyla satın alındı.',to_date('19-MAY-26','DD-MON-RR'),'SERVICE',2);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (9,1,'PURCHASE','Servis başarıyla satın alındı.',to_date('19-MAY-26','DD-MON-RR'),'SERVICE',2);
Insert into SYSTEM.AUDIT_LOGS (LOG_ID,SUBSCRIBER_ID,ACTION_TYPE,MESSAGE,CREATED_AT,ENTITY_TYPE,ENTITY_ID) values (10,null,'LOGIN','Successful login for user: admin',to_date('19-MAY-26','DD-MON-RR'),null,null);
--------------------------------------------------------
--  DDL for Index SYS_C008236
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008236" ON "SYSTEM"."AUDIT_LOGS" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AUDIT_LOGS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AUDIT_LOGS" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
